### ISSUE TITLE
Seems to have stopped working

### ISSUE THREAD

**Issue by angramainyuu** [sneat/patreon-downloader#16]
No matter which post I try to download the extension doesn't seem to be able to crawl the post, it just stays blank.

**Comment by angramainyuu** [comment]
![image](https://github.com/sneat/patreon-downloader/assets/98609452/66d41728-db5f-46a2-84f2-8375d5d880a1)

**Comment by bedsheet-insane** [comment]
Same issue for me. It seems that Patreon has changed how they handle files

**Comment by sneat** [comment]
Issue confirmed. Patreon has changed how the data is managed. I'll try to release an update this week to fix it.

**Comment by sneat** [comment]
@angramainyuu @bedsheet-insane I've submitted v1.1.2 to the web store for review. If you don't want to wait for that, you can [install it manually](https://github.com/sneat/patreon-downloader#install)

**Comment by angramainyuu** [comment]
> @angramainyuu @bedsheet-insane I've submitted v1.1.2 to the web store for review. If you don't want to wait for that, you can [install it manually](https://github.com/sneat/patreon-downloader#install)

works - thanks!
