### ISSUE TITLE
Button greyed out and will not do anything

### ISSUE THREAD

**Issue by gdork** [sneat/patreon-downloader#4]
I really want this extension to work, but when I try to use it, nothing happens. It is greyed out on my browser. I do not believe that it is working as of 11-10-21.

**Comment by sneat** [comment]
Hi @gdork 

It's still working for me on the posts that I generally use it on. Where are you tring to use it? Unfortunately Patreon can be a little inconsistent with their API data, so some styles of posts don't work as well.

If you can give me an example post link then I'll debug against that and do what I can to fix it.

**Comment by gdork** [comment]
Is there anything special that I need to do to make it work? Perhaps you can provide some simple instructions first. Maybe I am missing something.

**Comment by sneat** [comment]
No, nothing special to make it work. There will be some issue with the patreon data. 

Can you link me to the post you have been trying to use it on please @gdork ?

**Comment by gdork** [comment]
https://www.patreon.com/bellatrixortreat/posts

**Comment by sneat** [comment]
Do none of the posts work for you @gdork? Looking at the public one here, it works for me, does it work for you? https://www.patreon.com/posts/next-chapter-56761206

**Comment by gdork** [comment]
Thank you, I did not know that I had to go into individual posts. It works fine.

**Comment by sneat** [comment]
Good to hear @gdork. I’ll look to update the wording and instructions to make that clearer with a future update. Thank you for the feedback.
