### ISSUE TITLE
Avatar will be downloaded when downloading a post

### ISSUE THREAD

**Issue by fireattack** [sneat/patreon-downloader#6]
This only started to happen since a few days ago.

When downloading a post now, the avatar of the author will also be downloaded.

One example is https://www.patreon.com/posts/r-18-yi-chui-yi-60903888 (NSFW, behind paywall).

**Comment by fireattack** [comment]
Never mind, I just noticed it's an intended change (https://github.com/sneat/patreon-downloader/commit/611f99839682647f7ffb4c7f41003753ca89a1fe). 

I personally would like an option to disable it since I would have downloaded the same artist multiple times already, but I guess it really isn't a big deal.

**Comment by sneat** [comment]
I’ll leave this open and look to add some configuration options on the dialog.

**Comment by sneat** [comment]
Fixed in [release 1.0.8](https://github.com/sneat/patreon-downloader/releases/tag/1.0.8).
